Calculator: Milestone 4 to Develop
praz99/react_calculator pull request #4
Opened 2020-12-14 14:50 UTC by praz99

In milestone 4, I have implemented `calculate` and `operate` functions.

> The `operate` function takes two different numbers and a mathematical symbol (+, -, x, /) as arguments and performs an operation on the passed numbers according to the given symbol.
> The `calculate` function takes an object and a symbol as the arguments and perform some specific operations with the help of the `operate` function.

2020-12-14 15:19 UTC, MuriloRoque requested changes
## Status: Changes Requested :red_circle: 

### Hello @praz99 :wave: 

### You have done a very good job in this milestone, there are only some minor changes you need to make before moving on. Plase check my comments in your code.

Kindly make the requested changes and submit for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-12-14 15:19 UTC, MuriloRoque commented on src/logic/calculate.js
> +  }
- [ ] I suggest you put this in your `operate.js` module, and use the `mod` function from `Big.js`.

2020-12-14 15:19 UTC, MuriloRoque commented on src/logic/operate.js
> +      break;
- [ ] Please use `Big.js` functions `minus`, `mul` and `div` to make those operations, since you are using the library.

2020-12-15 09:24 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-12-15 10:24 UTC, merged